language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - COMPOSER_OPTIONS='install --prefer-source'

matrix:
   include:
     - php: 5.4
       env: COMPOSER_OPTIONS='update --prefer-lowest --prefer-source'

before_install:
  - composer self-update
  
before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer $COMPOSER_OPTIONS

script:
  - ./bin/phpspec run -v
